const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sections=['Survey setup','Visit information','Household profile','Household members','Demographics','Other demographics','Migration','Education','Employment','Health','Food security','Transport & finance','Disaster preparedness','Internet & public safety','Social protection','Water & sanitation','Housing characteristics','Consent & review'];
const seed={households:[{id:'HH-00452',head:'Maria Santos',address:'24 Mabini Street · Purok 2',status:'In progress',members:[{name:'Maria Santos',relationship:'Head',dob:'1980-03-04'},{name:'Juan Santos',relationship:'Spouse',dob:'1978-05-12'},{name:'Ana Santos',relationship:'Daughter',dob:'2009-08-17',sex:'Female',birth:'Yes'},{name:'Pedro Santos',relationship:'Son',dob:'2014-06-02'}],answers:{}},{id:'HH-00453',head:'Ramon Reyes',address:'8 Rizal Street · Purok 2',status:'Callback',members:[],answers:{}},{id:'HH-00454',head:'Elena Cruz',address:'16 Bonifacio Street · Purok 3',status:'Not started',members:[],answers:{}}]};let data;try{data=JSON.parse(localStorage.getItem('tala-demo-v1'))||structuredClone(seed)}catch{data=structuredClone(seed)}let route='home',hid=data.households[0]?.id||null,mid=2,filter='All',query='',section=0;const hh=()=>data.households.find(h=>h.id===hid),member=()=>hh()?.members[mid];
const paths={map:'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2Z M9 3v16 M15 5v16',home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',households:'M5 3h11v18H5z M9 7h3 M9 11h3 M9 15h3 M16 8h4v13',reports:'M4 3v18h17 M9 16v-5 M14 16V6 M19 16V9',profile:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 21v-3a8 8 0 0 1 16 0v3',members:'M10 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M2 20v-3a5 5 0 0 1 10 0v3 M17 4a3 3 0 0 1 0 6 M16 13a5 5 0 0 1 6 5v2',sections:'M8 5h13 M8 12h13 M8 19h13 M3 5h1 M3 12h1 M3 19h1',review:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M7 12l3 3 7-7'};function icon(n){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${(paths[n]||paths.households).split(' M').map((p,i)=>`<path d="${i?'M':''}${p}"/>`).join('')}</svg>`}
function nav(interview=false){let items=interview?[['overview','Overview'],['members','Members'],['sections','Sections'],['review','Review']]:[['home','Home'],['households','Households'],['map','Map'],['reports','Reports'],['profile','Profile']];return `<nav class="nav" aria-label="${interview?'Interview':'Main'} navigation">${items.map(([r,l])=>`<button class="${route===r?'active':''}" onclick="go('${r}')">${icon(r)}${l}</button>`).join('')}</nav>`}function header(title,sub='',back='home'){return `<header class="app-header">${back?`<button class="icon-btn" aria-label="Back" onclick="go('${back}')">‹</button>`:''}<div><h2>${esc(title)}</h2><small>${esc(sub)}</small></div><button class="avatar icon-btn" aria-label="Open profile" onclick="go('profile')">${esc((data.profile?.name||'JD').split(' ').map(n=>n[0]).slice(0,2).join(''))}</button></header>`}function shell(title,sub,body,interview=true,back='home',footer=''){return header(title,sub,back)+`<main class="scroll">${body}</main>`+(footer||nav(interview))}function actions(back,next,label='Save & continue'){return `<footer class="actions"><button class="secondary" onclick="go('${back}')">Back</button><button class="primary" onclick="${next}">${label}</button></footer>`}function age(d){if(!d)return '—';let now=new Date(),b=new Date(d+'T00:00:00');return now.getFullYear()-b.getFullYear()-(now.getMonth()<b.getMonth()||(now.getMonth()===b.getMonth()&&now.getDate()<b.getDate())?1:0)}
function householdList(){return data.households.filter(h=>(filter==='All'||h.status===filter)&&`${h.id} ${h.head} ${h.address}`.toLowerCase().includes(query.toLowerCase())).map(h=>`<button class="card row-card" onclick="hid='${h.id}';go('overview')"><span class="house-icon">⌂</span><span><strong>${esc(h.head)}</strong><small>${h.id} · ${esc(h.address.split(' · ')[1]||'Barangay Cogon')}</small><span class="badge ${h.status==='Callback'?'callback':h.status==='Demo reviewed'?'done':''}">● ${h.status}</span></span><span class="chevron">›</span></button>`).join('')||'<p class="empty">No matching households.<br>Try another name or household ID.</p>'}
function modal(html){$('#modal').innerHTML=html;$('#modal').showModal()}function consentStatement(){modal('<h3>Demo consent statement</h3><p>This preview demonstrates how an enumerator could explain collection and record a response. Use fictional information only.</p><p class="subtle">Before deployment, the barangay must supply an approved notice identifying purpose, authority, data use, retention, rights, and contact details. This text is not an official CBMS statement.</p><button class="primary wide" onclick="document.getElementById(\'modal\').close()">Close statement</button>')}

function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').style.display='none',3000)}

// Each launch/reload starts at Home; saved answers and household context remain intact.
history.replaceState(null,'',location.pathname+location.search+'#home');
