// Illustrative prototype questionnaire; official field/code mapping remains separate.
const field=(key,label,type='text',options=[],when=null,extra={})=>({key,label,type,options,when,...extra});
const yesno=(key,label,when=null)=>field(key,label,'choice',['Yes','No'],when);
const FORM=[
{route:'setup',fields:[field('enumerator','Enumerator name'),field('barangay','Barangay','select',['Barangay Cogon']),field('purok','Purok / zone'),field('interviewDate','Interview date','date')]},
{route:'visit',fields:[field('visitDate','Visit date','date'),field('visitResult','Visit result','select',['Interview started','Completed visit','Callback','No respondent','Refused']),field('callbackDate','Callback appointment','datetime-local',[],a=>a.visitResult==='Callback'),field('visitNotes','Visit notes','textarea',[],null,{optional:true})]},
{route:'household',fields:[field('head','Household head'),field('address','Address / purok'),field('respondent','Respondent name'),field('phone','Contact number (optional)','tel',[],null,{optional:true})]},
{route:'members',fields:[]},
{route:'demographics',person:true,fields:[field('name','Full name'),field('relationship','Relationship to household head','select',['Head','Spouse','Daughter','Son','Parent','Other']),field('sex','Sex','choice',['Male','Female']),field('dob','Date of birth','date',[],null,{past:true}),field('birth','Birth registered with the civil registry?','choice',['Yes','No',"Don't know"]),field('civilStatus','Civil status','select',['Single','Married','Widowed','Separated','Other','Prefer not to answer'])]},
{route:'other',person:true,fields:[yesno('nationalId','Has a National ID?'),yesno('soloParent','Identifies as a solo parent?'),yesno('disability','Has a disability?'),field('disabilityDetail','Disability description','text',[],a=>a.disability==='Yes'),field('seniorId','Has a senior citizen ID?','choice',['Yes','No','Not applicable'])]},
{route:'migration',person:true,fields:[field('citizenship','Citizenship'),yesno('moved','Moved into this barangay?'),field('previousResidence','Previous city / municipality','text',[],a=>a.moved==='Yes'),field('moveYear','Year moved','number',[],a=>a.moved==='Yes',{min:1900,max:new Date().getFullYear()}),yesno('overseas','Currently residing overseas?')]},
{route:'education',person:true,fields:[yesno('attending','Currently attending school?'),field('school','Type of school','select',['Public','Private'],a=>a.attending==='Yes'),field('reason','Reason for not attending','select',['Not yet school age','Completed schooling','Financial concerns','Working','Other','Prefer not to answer'],a=>a.attending==='No'),field('grade','Highest grade / year completed','select',['No grade completed','Kindergarten',...Array.from({length:12},(_,i)=>'Grade '+(i+1)),'College level','College graduate']),field('track','Program / track (optional)','text',[],a=>a.attending==='Yes',{optional:true})]},
{route:'employment',person:true,fields:[yesno('worked','Did this member work for pay or profit in the past 7 days?'),field('occupation','Occupation / job title','text',[],a=>a.worked==='Yes'),field('industry','Industry / business activity','text',[],a=>a.worked==='Yes'),field('employmentType','Employment type','select',['Employee','Self-employed','Employer','Paid family worker'],a=>a.worked==='Yes'),field('hours','Hours worked in the past 7 days','number',[],a=>a.worked==='Yes',{min:0,max:168}),yesno('looking','Currently looking for work?',a=>a.worked==='No'),field('notWorkingReason','Main reason for not working','select',['Student','Below working age','Homemaking / caregiving','Retired','Health condition','Unable to find work','Other'],a=>a.worked==='No'),yesno('available','Available to start work?',a=>a.worked==='No'&&a.looking==='Yes')]},
{route:'health',fields:[yesno('illness','Did anyone need medical care in the past 30 days?'),field('treatment','Where was care sought?','select',['Barangay health center','Public hospital','Private facility','No care sought','Other'],a=>a.illness==='Yes'),yesno('healthAccess','Can the household reach a health facility when needed?')]},
{route:'food',fields:[field('foodWorry','In the past 30 days, how often did the household worry about food?','select',['Never','Rarely','Sometimes','Often']),yesno('skippedMeals','Did anyone skip a meal due to lack of resources?'),yesno('foodAssistance','Received food assistance in the past 30 days?')]},
{route:'transport',fields:[field('transport','Usual mode of transport','select',['Walking','Bicycle','Motorcycle','Tricycle','Jeepney / bus','Private car','Other']),field('accounts','Financial accounts held','multi',['Bank','Digital bank','E-money','Cooperative','None','Prefer not to answer'])]},
{route:'disaster',fields:[field('hazards','Hazards experienced in the past year','multi',['Flood','Typhoon','Earthquake','Fire','Landslide','None']),yesno('evacuationKnown','Knows the designated evacuation area?'),field('evacuation','Evacuation area','text',[],a=>a.evacuationKnown==='Yes'),yesno('emergencyKit','Has an emergency kit?')]},
{route:'internet',fields:[yesno('internet','Does anyone have internet access?'),field('connection','Internet connection','select',['Mobile data','Fiber / cable','Public Wi-Fi','Other'],a=>a.internet==='Yes'),field('safety','How safe does the household feel in the neighborhood?','select',['Very safe','Somewhat safe','Somewhat unsafe','Very unsafe','Prefer not to answer'])]},
{route:'protection',fields:[field('programs','Programs covering household members','multi',['PhilHealth','SSS','GSIS','4Ps','Senior citizen assistance','PWD assistance','None','Prefer not to answer']),yesno('assistance','Received other government assistance in the past year?'),field('assistanceDetail','Type of assistance','text',[],a=>a.assistance==='Yes')]},
{route:'water',fields:[field('water','Main drinking water source','select',['Piped into dwelling','Piped to yard or plot','Public tap or standpipe','Tube well or borehole','Protected well','Spring','Rainwater','Tanker truck','Other']),field('toilet','Toilet facility','select',['Flush / pour flush','Pit latrine','Shared toilet','No toilet','Other']),field('waste','Waste disposal practices','multi',['Collection service','Composting','Recycling','Burning','Other']),yesno('handwashing','Has a handwashing place with soap and water?')]},
{route:'housing',fields:[field('roof','Main roofing material','select',['Metal roofing sheets','Concrete / clay / slate tile','Wood / bamboo','Sod / thatch','Makeshift / salvaged','Other']),field('walls','Main wall material','select',['Concrete / brick','Wood','Bamboo','Mixed materials','Other']),field('tenure','Housing tenure','select',['Owned','Rented','Rent-free with permission','Other']),yesno('electricity','Has electricity?'),field('rooms','Number of sleeping rooms','number',[],null,{min:0,max:50})]},
{route:'consent',fields:[]}];
