// Local coordinates are independent of the map provider. No household is geocoded automatically.
let leafletMap=null,locationMarker=null,accuracyCircle=null,mapGeneration=0;
let locationDrafts=new Map(),removedHousehold=null;
const SERVICE_AREA_NAME='Barangay Cogon, Ormoc City, Leyte, Philippines';
const DEFAULT_MAP_CENTER=[11.0176,124.6031];
// Approximate prototype working extent, NOT an official barangay boundary polygon.
const SERVICE_AREA_BOUNDS=[[11.0116,124.5971],[11.0236,124.6091]];
function inServiceArea(p){return validPoint(p)&&p.lat>=SERVICE_AREA_BOUNDS[0][0]&&p.lat<=SERVICE_AREA_BOUNDS[1][0]&&p.lng>=SERVICE_AREA_BOUNDS[0][1]&&p.lng<=SERVICE_AREA_BOUNDS[1][1]}
function localAddress(h){return [h.address,SERVICE_AREA_NAME].filter(Boolean).join(', ')}
function validPoint(p){return p&&typeof p.lat==='number'&&Number.isFinite(p.lat)&&p.lat>=-90&&p.lat<=90&&typeof p.lng==='number'&&Number.isFinite(p.lng)&&p.lng>=-180&&p.lng<=180}
function googleMapUrl(h,directions=false){const p=h.location;const value=validPoint(p)?`${p.lat},${p.lng}`:localAddress(h);return 'https://www.google.com/maps/'+(directions?'dir/':'search/')+'?'+new URLSearchParams({api:'1',[directions?'destination':'query']:value})}
function locationCard(h){const p=h.location;return `<div class="card location-card"><span class="overline">HOUSEHOLD LOCATION</span>${validPoint(p)&&!inServiceArea(p)?'<p class="error">Saved pin is outside the Cogon working area. Please correct it.</p>':''}<h3>${validPoint(p)?'Location tagged':'No location tagged'}</h3>${validPoint(p)&&p.addressAtCapture!==h.address?'<p class="error">Address changed. Check and save the pin again.</p>':''}<p class="subtle">${validPoint(p)?`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)} · ${p.source==='device'?'Device location':'Manually placed'}`:'Capture your location at the dwelling, or place the pin yourself.'}</p><button class="secondary wide" onclick="go('location')">${validPoint(p)?'View / edit location':'Tag household location'}</button>${validPoint(p)?`<a class="map-link" href="${esc(googleMapUrl(h,true))}" target="_blank" rel="noopener noreferrer">Directions in Google Maps ↗</a>`:''}</div>`}
function draftFor(){if(!locationDrafts.has(hid)){locationDrafts.set(hid,hh().location?{...hh().location,confirmed:false}:{lat:'',lng:'',source:'manual',notes:'',confirmed:false})}return locationDrafts.get(hid)}
function locationScreen(){const h=hh(),d=draftFor(),p=h.location;return shell('Household location',h.id,`<h3>${esc(h.head)}</h3><p class="subtle">${esc(h.address)}</p><div class="map-panel"><div id="household-map" class="geo-map" aria-label="Map for choosing household location"></div><div class="map-provider">Cogon, Ormoc · Tap to place, drag to adjust</div></div><p class="subtle tiny">Approximate Cogon working area; official barangay boundary not yet supplied.</p><p id="map-status" class="subtle" role="status"></p><button id="capture-location" class="primary wide" onclick="captureLocation()">◎ Use my current location</button><p class="subtle tiny">Use this while at the household. Device location may be approximate; check the pin before saving.</p><div class="coordinate-grid"><div><label class="question" for="location-lat">Latitude</label><input class="field" id="location-lat" inputmode="decimal" value="${esc(d.lat)}" placeholder="e.g. 11.017600" oninput="readCoordinateFields()"></div><div><label class="question" for="location-lng">Longitude</label><input class="field" id="location-lng" inputmode="decimal" value="${esc(d.lng)}" placeholder="e.g. 124.603100" oninput="readCoordinateFields()"></div></div><p id="coordinate-error" class="error" role="alert"></p><p id="accuracy-status" class="subtle"></p><label class="question" for="location-notes">Landmark / directions (optional)</label><textarea id="location-notes" class="field" rows="2" placeholder="Entrance beside the barangay hall…" oninput="draftFor().notes=this.value">${esc(d.notes||'')}</textarea><label class="radio confirm-location"><input id="location-confirmed" type="checkbox" onchange="draftFor().confirmed=this.checked">I checked that this pin marks the household.</label><button class="primary wide" onclick="saveHouseholdLocation()">Save household location</button><button class="secondary wide" onclick="discardLocationDraft()">Discard pin changes</button><div class="map-links"><a class="map-link" href="${esc('https://www.google.com/maps/search/?'+new URLSearchParams({api:'1',query:localAddress(h)}))}" target="_blank" rel="noopener noreferrer">Search address in Google Maps ↗</a>${validPoint(p)?`<a class="map-link" href="${esc(googleMapUrl(h))}" target="_blank" rel="noopener noreferrer">Open saved pin in Google Maps ↗</a><a class="map-link" href="${esc(googleMapUrl(h,true))}" target="_blank" rel="noopener noreferrer">Directions to saved pin ↗</a><button class="link danger-text" onclick="clearLocationDialog()">Remove saved location</button>`:''}</div><p class="subtle tiny">Google links use the saved coordinates or address. Pins are saved in this app; they are not published as public Google Maps places.</p>`,true,'overview')}
function mapScreen(){let tagged=data.households.filter(h=>inServiceArea(h.location));return shell('Household map',`Cogon, Ormoc · ${tagged.length} pins in area`,`<div class="map-panel"><div id="household-map" class="geo-map registry-map" aria-label="Map of saved household locations"></div><div class="map-provider">Cogon, Ormoc · Select a pin to view its household</div></div><p id="map-status" class="subtle" role="status"></p>${!tagged.length?'<div class="notice">No household locations saved yet. Choose a household below and tag its location.</div>':''}<div class="heading-row"><h3>Locate a household</h3></div><input class="search" aria-label="Search mapped households" placeholder="Search name, address or ID" oninput="document.getElementById('map-households').innerHTML=mapHouseholdList(this.value)"><div id="map-households">${mapHouseholdList('')}</div>${!data.households.length?'<button class="primary wide" onclick="newHouse()">Register a household</button>':''}<p class="subtle tiny">Only pins in the Cogon working area appear. Existing out-of-area pins are retained for correction. Online map tiles are required; coordinates stay available if the basemap cannot load.</p>`,false,'home')}
function mapHouseholdList(q){return data.households.filter(h=>`${h.head} ${h.address} ${h.id}`.toLowerCase().includes(q.toLowerCase())).map(h=>`<button class="card row-card" onclick="hid='${h.id}';go('location')"><span class="house-icon">⌖</span><span><strong>${esc(h.head)}</strong><small>${h.id} · ${inServiceArea(h.location)?'Location tagged':validPoint(h.location)?'Outside area · correct pin':'No pin yet'}</small></span><span class="chevron">›</span></button>`).join('')||'<p class="empty">No matching households.</p>'}
function disposeMap(){mapGeneration++;if(leafletMap){leafletMap.stop();leafletMap.remove();leafletMap=null}locationMarker=null;accuracyCircle=null}
function markerIcon(){return L.divIcon({className:'household-pin',html:'<span>⌂</span>',iconSize:[32,38],iconAnchor:[16,36]})}
function mountMap(){if(!window.L){$('#map-status').textContent='Map library unavailable. Enter coordinates below or open Google Maps.';return}const selecting=route==='location',d=selecting?draftFor():null,tagged=data.households.filter(h=>inServiceArea(h.location));const initial=selecting&&inServiceArea(d)?[d.lat,d.lng]:tagged.length?[tagged[0].location.lat,tagged[0].location.lng]:DEFAULT_MAP_CENTER;leafletMap=L.map('household-map',{scrollWheelZoom:false,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false,minZoom:16,maxZoom:19,maxBounds:SERVICE_AREA_BOUNDS,maxBoundsViscosity:1}).setView(initial,(selecting&&inServiceArea(d))||tagged.length?17:16);const layer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> contributors'}).addTo(leafletMap);layer.on('tileerror',()=>{if($('#map-status'))$('#map-status').textContent='Some map tiles could not load. Check your connection; coordinate entry and saved locations still work.'});if(selecting){leafletMap.on('click',e=>setDraftPoint(e.latlng.lat,e.latlng.lng,'manual'));if(inServiceArea(d))drawDraftPin();updateLocationDetails()}else{for(const h of tagged){const content=document.createElement('div'),title=document.createElement('strong'),address=document.createElement('p'),button=document.createElement('button');title.textContent=h.head;address.textContent=h.id;button.textContent='Open household';button.className='secondary';button.onclick=()=>{hid=h.id;go('overview')};content.append(title,address,button);L.marker([h.location.lat,h.location.lng],{icon:markerIcon(),title:h.head,alt:'Household '+h.id}).addTo(leafletMap).bindPopup(content)}if(tagged.length>1)leafletMap.fitBounds(tagged.map(h=>[h.location.lat,h.location.lng]),{padding:[30,30],maxZoom:17})}leafletMap.invalidateSize()}
function drawDraftPin(){if(!leafletMap)return;const d=draftFor();if(accuracyCircle){accuracyCircle.remove();accuracyCircle=null}if(!inServiceArea(d)){if(locationMarker){locationMarker.remove();locationMarker=null}return}if(!locationMarker){locationMarker=L.marker([d.lat,d.lng],{icon:markerIcon(),draggable:true,title:'Drag to adjust household location',alt:'Proposed household location'}).addTo(leafletMap);locationMarker.on('dragend',()=>{const p=locationMarker.getLatLng();setDraftPoint(p.lat,p.lng,'manual')})}else locationMarker.setLatLng([d.lat,d.lng]);if(d.source==='device'&&Number.isFinite(d.accuracy))accuracyCircle=L.circle([d.lat,d.lng],{radius:d.accuracy,weight:1,color:'#174f9f',fillOpacity:.08}).addTo(leafletMap)}
function setDraftPoint(lat,lng,source,accuracy=null,capturedAt=null){const d=draftFor();Object.assign(d,{lat:Number(lat.toFixed(6)),lng:Number(lng.toFixed(6)),source,accuracy,capturedAt:capturedAt||new Date().toISOString(),confirmed:false});$('#location-lat').value=d.lat;$('#location-lng').value=d.lng;$('#location-confirmed').checked=false;drawDraftPin();updateLocationDetails()}
function readCoordinateFields(){const d=draftFor(),lat=$('#location-lat').value.trim(),lng=$('#location-lng').value.trim();Object.assign(d,{lat:lat===''?'':Number(lat),lng:lng===''?'':Number(lng),source:'manual',accuracy:null,capturedAt:new Date().toISOString(),confirmed:false});$('#location-confirmed').checked=false;drawDraftPin();if(inServiceArea(d)&&leafletMap)leafletMap.setView([d.lat,d.lng],17);updateLocationDetails()}
function updateLocationDetails(){const d=draftFor();$('#coordinate-error').textContent=validPoint(d)?(inServiceArea(d)?'':'This pin is outside the Cogon working area. Choose a location within the displayed area.'):d.lat===''&&d.lng===''?'':'Enter latitude from −90 to 90 and longitude from −180 to 180.';$('#accuracy-status').textContent=!validPoint(d)?'No pin selected. The initial map view is not a household location.':d.source==='device'?`Device estimate: ±${Math.round(d.accuracy)} m. ${d.accuracy>50?'Low accuracy — move outdoors or adjust the pin.':'Check the dwelling before saving.'}`:'Manually placed pin · GPS accuracy not measured.'}
function captureLocation(){if(!navigator.geolocation)return toast('This browser does not support device location. Enter coordinates instead.');const id=hid,gen=mapGeneration,button=$('#capture-location');button.disabled=true;button.textContent='Finding your location…';navigator.geolocation.getCurrentPosition(pos=>{if(gen!==mapGeneration||route!=='location'||id!==hid)return;button.disabled=false;button.textContent='◎ Use my current location';setDraftPoint(pos.coords.latitude,pos.coords.longitude,'device',pos.coords.accuracy,new Date(pos.timestamp).toISOString());if(inServiceArea(draftFor()))leafletMap?.setView([pos.coords.latitude,pos.coords.longitude],17);toast(inServiceArea(draftFor())?'Location captured. Check the pin, then save.':'Your device is outside the Cogon working area. Place the household pin manually.');},err=>{if(gen!==mapGeneration||route!=='location'||id!==hid)return;button.disabled=false;button.textContent='◎ Use my current location';$('#map-status').textContent=err.code===1?'Location permission denied. Allow location in browser settings, or place the pin manually.':err.code===3?'Location request timed out. Try again outdoors or enter coordinates.':'Device location unavailable. Place the pin manually or enter coordinates.';},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
function saveHouseholdLocation(){const d=draftFor();if(!validPoint(d)){updateLocationDetails();return toast('Choose a valid location first.')}if(!inServiceArea(d)){updateLocationDetails();return toast('Household locations must be within the Cogon working area.')}if(!d.confirmed)return toast('Confirm that the pin marks the household.');hh().location={lat:d.lat,lng:d.lng,source:d.source,accuracy:d.source==='device'?d.accuracy:null,capturedAt:d.capturedAt||new Date().toISOString(),verifiedAt:new Date().toISOString(),notes:d.notes||'',addressAtCapture:hh().address};invalidate();save();locationDrafts.delete(hid);toast('Household location saved.');go('overview')}
function discardLocationDraft(){locationDrafts.delete(hid);render();toast('Unsaved pin changes discarded.')}
function clearLocationDialog(){const id=hid;modal('<h3>Remove saved location?</h3><p>The household record will remain. Its saved pin and location notes will be removed.</p><button class="danger wide" id="confirm-clear-location">Remove location</button><button class="secondary wide" onclick="document.getElementById(\'modal\').close()">Cancel</button>');$('#confirm-clear-location').onclick=()=>{const h=data.households.find(h=>h.id===id);if(h){delete h.location;locationDrafts.delete(id);invalidate();save()}$('#modal').close();render()}}
function removeHouseholdDialog(){const h=hh(),id=h.id;modal(`<h3>Remove household?</h3><p><strong>${esc(h.head)}</strong><br>${id}</p><p class="subtle">This removes the household, its ${h.members.length} member records, answers, and saved location from this browser. You can undo the latest removal until this page is refreshed.</p><button class="danger wide" id="confirm-remove-household">Remove household and records</button><button class="secondary wide" onclick="$('#modal').close()">Cancel</button>`);$('#confirm-remove-household').onclick=()=>{const i=data.households.findIndex(h=>h.id===id);if(i<0)return;data.nextHouseholdNumber=Math.max(data.nextHouseholdNumber||455,...data.households.map(h=>Number(h.id.slice(3))+1));removedHousehold={record:data.households[i],index:i};data.households.splice(i,1);locationDrafts.delete(id);hid=data.households[0]?.id||null;mid=0;save();$('#modal').close();go('home');showHouseholdUndo()}}
function showHouseholdUndo(){clearTimeout(window.tt);const t=$('#toast');t.replaceChildren(document.createTextNode('Household removed. '));const b=document.createElement('button');b.textContent='Undo';b.className='undo-button';b.onclick=restoreRemovedHousehold;t.append(b);t.style.display='block'}

function restoreRemovedHousehold(){if(!removedHousehold)return;data.households.splice(Math.min(removedHousehold.index,data.households.length),0,removedHousehold.record);hid=removedHousehold.record.id;removedHousehold=null;save();go('overview');toast('Household restored.')}

