async function reloadAndReturn(page){const previous=await page.evaluate(()=>route);await page.reload();if(await page.evaluate(()=>route)!=='home'||!page.url().endsWith('#home'))throw Error('Reload did not open Home');await page.evaluate(r=>go(r),previous)}
const {chromium}=require('playwright');const assert=(v,m)=>{if(!v)throw Error(m)};
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const context=await browser.newContext({viewport:{width:390,height:844},geolocation:{latitude:11.0176,longitude:124.6031,accuracy:12},permissions:['geolocation']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.getByRole('button',{name:/Maria Santos/}).click();
// Confirmation cancellation preserves all records.
await page.getByRole('button',{name:'Remove household',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert(await page.evaluate(()=>data.households.length)===3,'Cancel removed household');
await page.getByRole('button',{name:'Tag household location',exact:true}).click();await page.waitForSelector('.leaflet-container');
assert(await page.evaluate(()=>leafletMap.getMinZoom())===16,'Map allows national zoom');
assert(await page.evaluate(()=>leafletMap.getCenter().distanceTo(L.latLng(DEFAULT_MAP_CENTER)))<2,'Wrong Cogon center');
await page.getByLabel('Latitude',{exact:true}).fill('14.5995');await page.getByLabel('Longitude',{exact:true}).fill('120.9842');await page.getByLabel('I checked that this pin marks the household.').check();await page.getByRole('button',{name:'Save household location'}).click();assert(await page.evaluate(()=>!hh().location),'Outside Cogon pin saved');
await page.getByRole('button',{name:'Discard pin changes'}).click();assert(await page.evaluate(()=>!hh().location),'Initial map fabricated a household location');await page.getByRole('button',{name:'Save household location'}).click();assert(await page.evaluate(()=>!hh().location),'Saved blank pin');await page.getByLabel('Latitude',{exact:true}).fill('100');await page.getByLabel('Longitude',{exact:true}).fill('120');assert(await page.locator('#coordinate-error').textContent(),'Invalid range not caught');
// Real browser Geolocation API with a simulated position and permission.
await page.getByRole('button',{name:'Use my current location'}).click();await page.waitForFunction(()=>draftFor().source==='device');assert(await page.evaluate(()=>draftFor().accuracy)===12,'GPS accuracy not retained');await page.getByRole('button',{name:'Save household location'}).click();assert(await page.evaluate(()=>!hh().location),'Saved unconfirmed pin');await page.getByLabel('I checked that this pin marks the household.').check();await page.getByLabel('Landmark / directions (optional)').fill('Test entrance');await page.getByRole('button',{name:'Save household location'}).click();const saved=await page.evaluate(()=>hh().location);assert(saved.lat===11.0176&&saved.source==='device'&&saved.notes==='Test entrance','Wrong saved capture');const link=await page.getByRole('link',{name:'Directions in Google Maps'}).getAttribute('href');const url=new URL(link);assert(url.searchParams.get('destination')==='11.0176,124.6031','Google destination not exact');assert(!link.includes('Santos'),'Private name included in Maps URL');await reloadAndReturn(page);assert(await page.getByRole('heading',{name:'Location tagged',exact:true}).count()===1,'Pin lost on reload');
await page.getByRole('button',{name:'View / edit location'}).click();await page.getByLabel('Latitude',{exact:true}).fill('11.018000');assert(await page.evaluate(()=>draftFor().accuracy===null&&draftFor().source==='manual'),'Manual correction retained GPS accuracy');await page.getByRole('button',{name:'Discard pin changes'}).click();assert(await page.getByLabel('Latitude',{exact:true}).inputValue()==='11.0176','Discard failed');
// Interactive click and marker drag handlers update the draft, never auto-save.
await page.locator('#household-map').click({position:{x:140,y:160}});assert(await page.evaluate(()=>draftFor().source)==='manual','Map click did not place pin');await page.evaluate(()=>{locationMarker.setLatLng([11.0181,124.6041]);locationMarker.fire('dragend')});assert(await page.getByLabel('Latitude',{exact:true}).inputValue()==='11.0181','Dragged pin not reflected');assert(await page.evaluate(()=>hh().location.lat)===11.0176,'Draft overwrote saved location');await page.getByLabel('I checked that this pin marks the household.').check();await page.getByRole('button',{name:'Save household location'}).click();
await page.evaluate(()=>go('map'));assert(await page.locator('.household-pin').count()===1,'Saved marker missing on registry map');await page.locator('.household-pin').click();await page.getByRole('button',{name:'Open household',exact:true}).click();assert(await page.getByRole('heading',{name:'HH-00452',exact:true}).count()===1,'Marker opened wrong household');
await page.getByRole('button',{name:'View / edit location'}).click();await context.setGeolocation({latitude:11.0181,longitude:124.6041,accuracy:500});await page.getByRole('button',{name:'Use my current location'}).click();await page.getByText(/Low accuracy/).waitFor();await page.getByRole('button',{name:'Discard pin changes'}).click();await context.clearPermissions();await context.grantPermissions([]);await page.evaluate(()=>{navigator.geolocation.getCurrentPosition=(ok,error)=>error({code:1})});await page.getByRole('button',{name:'Use my current location'}).click();await page.getByText(/Location permission denied/).waitFor();assert(await page.evaluate(()=>hh().location.lat)===11.0181,'Denied permission modified saved pin');
// Stale async callbacks must not change a different household.
await page.evaluate(()=>{navigator.geolocation.getCurrentPosition=(ok)=>window.delayedGeo=ok});await page.getByRole('button',{name:'Use my current location'}).click();await page.evaluate(()=>{hid='HH-00453';go('location');window.delayedGeo({coords:{latitude:10,longitude:120,accuracy:4},timestamp:Date.now()})});assert(await page.evaluate(()=>!validPoint(draftFor())),'Late GPS result crossed household boundary');
await page.evaluate(()=>{hid='HH-00452';go('location')});await page.getByRole('button',{name:'Remove saved location'}).click();await page.getByRole('button',{name:'Remove location',exact:true}).click();assert(await page.evaluate(()=>!hh().location),'Remove pin failed');
// Delete and undo restores nested member/answer state.
await page.evaluate(()=>go('overview'));await page.getByRole('button',{name:'Remove household',exact:true}).click();await page.getByRole('button',{name:'Remove household and records'}).click();assert(await page.evaluate(()=>data.households.length)===2,'Remove failed');await page.getByRole('button',{name:'Undo',exact:true}).click();assert(await page.evaluate(()=>hh().members.length)===4,'Undo failed to restore members');
// Delete the final record, refresh, visit map/reports, then register again without ID reuse.
for(let i=0;i<3;i++){await page.evaluate(()=>{hid=data.households[0].id;go('overview')});await page.getByRole('button',{name:'Remove household',exact:true}).click();await page.getByRole('button',{name:'Remove household and records'}).click()}
await reloadAndReturn(page);assert(await page.evaluate(()=>data.households.length)===0,'Deleted data reappeared');await page.getByRole('button',{name:'Map',exact:true}).click();assert(await page.getByText('No matching households.',{exact:true}).count()===1,'Empty map failed');await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Register a household'}).click();await page.getByLabel('Household head',{exact:true}).fill('Map Demo');await page.getByLabel('Address / purok').fill('Demo Address');await page.getByRole('button',{name:'Create household',exact:true}).click();assert(await page.evaluate(()=>hh().id)==='HH-00455','Deleted household ID reused');
await page.evaluate(()=>go('location'));await page.getByLabel('Latitude',{exact:true}).fill('11.0176');await page.getByLabel('Longitude',{exact:true}).fill('124.6031');await page.getByLabel('I checked that this pin marks the household.').check();await page.getByRole('button',{name:'Save household location'}).click();await page.evaluate(()=>go('map'));await page.waitForTimeout(1500);await page.screenshot({path:'preview-household-map.png'});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Mobile overflow');assert(!errors.length,errors.join('\n'));console.log(JSON.stringify({passed:true,pageErrors:errors,checks:['delete cancel','delete and undo','delete all and refresh','non-reused IDs','coordinate bounds','GPS capture and accuracy','confirmation required','coordinate persistence','exact Google links','map click and drag','all-household marker navigation','low accuracy','permission denial','stale GPS callback isolation','discard draft','remove pin','empty registry navigation','mobile layout']}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
