async function reloadAndReturn(page){const previous=await page.evaluate(()=>route);await page.reload();if(await page.evaluate(()=>route)!=='home'||!page.url().endsWith('#home'))throw Error('Reload did not open Home');await page.evaluate(r=>go(r),previous)}
const {chromium}=require('playwright');
const assert=(condition,message)=>{if(!condition)throw Error(message)};
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');
// Regression: editing a long form must preserve its scroll and existing input nodes.
await page.setViewportSize({width:390,height:640});
await page.evaluate(()=>{mid=2;member().worked='Yes';go('employment')});
await page.getByLabel('Hours worked in the past 7 days').scrollIntoViewIfNeeded();
const scrollBefore=await page.locator('.scroll').evaluate(el=>el.scrollTop);
assert(scrollBefore>0,'Scroll regression requires a scrolled form');
await page.getByLabel('Hours worked in the past 7 days').fill('35');
await page.getByLabel('Hours worked in the past 7 days').evaluate(el=>{window.originalInput=el;el.blur()});
assert(await page.evaluate(()=>window.originalInput===document.getElementById('field-hours')),'Ordinary edit replaced the input');
assert(Math.abs(await page.locator('.scroll').evaluate(el=>el.scrollTop)-scrollBefore)<2,'Text edit reset scroll');
await page.evaluate(()=>go('water'));
await page.getByLabel('Recycling',{exact:true}).scrollIntoViewIfNeeded();
const multiScroll=await page.locator('.scroll').evaluate(el=>el.scrollTop);
await page.getByLabel('Recycling',{exact:true}).check();
assert(Math.abs(await page.locator('.scroll').evaluate(el=>el.scrollTop)-multiScroll)<2,'Checkbox refresh reset scroll');
await page.evaluate(()=>{go('employment');member().worked='No';member().looking='No';render()});
await page.getByRole('group',{name:'Currently looking for work?'}).scrollIntoViewIfNeeded();
const branchScroll=await page.locator('.scroll').evaluate(el=>el.scrollTop);
await page.getByRole('group',{name:'Currently looking for work?'}).getByRole('button',{name:'Yes',exact:true}).click();
assert(Math.abs(await page.locator('.scroll').evaluate(el=>el.scrollTop)-branchScroll)<2,'Conditional follow-up reset scroll');
await page.evaluate(()=>go('members'));
assert(await page.locator('.scroll').evaluate(el=>el.scrollTop)===0,'New screen did not start at top');
await page.evaluate(()=>{data=structuredClone(seed);data.profile={name:'Jamie Dela Cruz',barangay:'Barangay 001'};for(const h of data.households){h.answers.head=h.head;h.answers.address=h.address}mid=2;go('home')});
await page.setViewportSize({width:390,height:844});
// Isolated browser context: no changes to the user's saved prototype.
await page.getByRole('button',{name:/Maria Santos/}).click();await page.getByRole('button',{name:'Household members',exact:false}).click();await page.getByRole('button',{name:/Ana Santos/}).click();await page.getByRole('button',{name:'Employment',exact:true}).click();await page.getByRole('button',{name:'Save member',exact:true}).click();assert(await page.locator('.error').count()>0,'Required employment answer was not validated');
await page.getByRole('button',{name:'Yes',exact:true}).click();await page.getByLabel('Occupation / job title').fill('Shop assistant');await page.getByLabel('Industry / business activity').fill('Retail');await page.getByLabel('Employment type',{exact:true}).selectOption('Employee');await page.getByLabel('Hours worked in the past 7 days').fill('200');await page.getByRole('button',{name:'Save member',exact:true}).click();assert(await page.getByText('Enter a whole number from 0 to 168.').count()===1,'Hours bound missing');await page.getByLabel('Hours worked in the past 7 days').fill('40');await reloadAndReturn(page);assert(await page.getByLabel('Occupation / job title').inputValue()==='Shop assistant','Employment persistence failed');assert(await page.getByRole('heading',{name:'Ana Santos'}).count()===1,'Selected member lost after reload');
await page.getByRole('button',{name:'No',exact:true}).first().click();assert(await page.getByLabel('Occupation / job title').count()===0,'Employment branch not hidden');assert(await page.evaluate(()=>member().occupation===undefined),'Hidden occupation retained');await page.getByRole('group',{name:'Currently looking for work?'}).getByRole('button',{name:'Yes',exact:true}).click();await page.getByLabel('Main reason for not working').selectOption('Unable to find work');await page.getByRole('group',{name:'Available to start work?'}).getByRole('button',{name:'Yes',exact:true}).click();await page.screenshot({path:'preview-employment.png'});await page.getByRole('button',{name:'Save member',exact:true}).click();
// Every section has a working destination; no planned-section dead end.
for(let i=0;i<18;i++){await page.evaluate(i=>openSection(i),i);assert(await page.locator('.scroll').count()===1,'Missing section '+i);assert(!await page.getByText('PLANNED SECTION',{exact:true}).count(),'Placeholder remains '+i)}
// Exclusivity of None and real multiple selections.
await page.evaluate(()=>go('transport'));await page.getByLabel('Bank',{exact:true}).check();await page.getByLabel('None',{exact:true}).check();assert(!await page.getByLabel('Bank',{exact:true}).isChecked(),'None did not clear other financial answers');await page.getByLabel('E-money',{exact:true}).check();assert(!await page.getByLabel('None',{exact:true}).isChecked(),'Financial answer did not clear None');
// Create a second household, add and remove a member, retain context on refresh.
await page.evaluate(()=>go('home'));await page.getByRole('button',{name:'Register a household'}).click();await page.getByLabel('Household head',{exact:true}).fill('Prototype Family');await page.getByLabel('Address / purok').fill('Sample Street');await page.getByRole('button',{name:'Create household',exact:true}).click();await reloadAndReturn(page);assert(await page.evaluate(()=>hh().head)==='Prototype Family','Household context lost');await page.evaluate(()=>go('members'));await page.getByRole('button',{name:'Add household member'}).click();await page.getByLabel('Full name',{exact:true}).fill('Prototype Person');await page.getByRole('button',{name:'Add member',exact:true}).click();await page.locator('#field-name').fill('Renamed Person');await reloadAndReturn(page);assert(await page.locator('#field-name').inputValue()==='Renamed Person','Name edit lost');
// Fill each form through real controls for one household/member.
const fillForm=async(i)=>{await page.evaluate(i=>openSection(i),i);for(let guard=0;guard<50;guard++){const todo=await page.evaluate(()=>{let f=FORM.find(x=>x.route===route);let a=targetFor(f);return f.fields.filter(x=>visible(x,a)&&errorFor(x,a)).map(x=>({key:x.key,label:x.label,type:x.type,options:x.options,min:x.min}));});if(!todo.length)return;let x=todo[0];if(x.type==='choice'){await page.getByRole('group',{name:x.label,exact:true}).getByRole('button',{name:x.options[0],exact:true}).click()}else if(x.type==='multi'){await page.getByRole('group',{name:x.label,exact:true}).getByLabel(x.options[0],{exact:true}).check()}else if(x.type==='select'){await page.getByLabel(x.label,{exact:true}).selectOption(x.options[0])}else{let value=x.type==='date'?(x.key==='dob'?'1990-01-01':'2026-09-23'):x.type==='number'?String(Math.max(x.min||0,1)):'Demo answer';await page.getByLabel(x.label,{exact:true}).fill(value);await page.getByLabel(x.label,{exact:true}).blur()}}throw Error('Form completion loop '+i)};
for(let i=0;i<17;i++)if(i!==3)await fillForm(i);
await page.evaluate(()=>go('consent'));await page.getByRole('button',{name:'Yes',exact:true}).click();const canvas=page.locator('#signature'),box=await canvas.boundingBox();await page.mouse.move(box.x+20,box.y+30);await page.mouse.down();await page.mouse.move(box.x+80,box.y+70,{steps:5});await page.mouse.up();assert(await page.evaluate(()=>!!hh().answers.signature),'Signature not stored');await page.getByRole('button',{name:'No',exact:true}).click();assert(await page.evaluate(()=>!hh().answers.signature),'Signature not cleared after refusal');await page.getByRole('button',{name:'Review interview'}).click();assert(await page.getByRole('button',{name:'Finish demo review'}).isDisabled(),'Refusal allowed review');await page.evaluate(()=>go('consent'));await page.getByRole('button',{name:'Yes',exact:true}).click();await page.getByLabel('Or type a fictional name as your signature').fill('Demo Signer');await page.getByRole('button',{name:'Review interview'}).click();assert(!await page.getByRole('button',{name:'Finish demo review'}).isDisabled(),'Complete household not eligible');await page.getByRole('button',{name:'Finish demo review'}).click();assert(await page.evaluate(()=>hh().status)==='Demo reviewed','Finish review failed');await page.evaluate(()=>go('employment'));await page.getByLabel('Occupation / job title').fill('Updated role');assert(await page.evaluate(()=>hh().status)==='In progress','Editing retained reviewed state');
await page.evaluate(()=>go('visit'));await page.getByLabel('Visit result',{exact:true}).selectOption('Callback');await page.getByLabel('Callback appointment').fill('2026-10-01T14:00');await reloadAndReturn(page);assert(await page.getByLabel('Callback appointment').inputValue()==='2026-10-01T14:00','Callback lost');assert(await page.evaluate(()=>hh().status)==='Callback','Callback status failed');
await page.evaluate(()=>go('reports'));const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export demo records JSON'}).click();const download=await downloadPromise;assert(download.suggestedFilename()==='tala-demo-records.json','Export failed');await page.evaluate(()=>go('profile'));await page.getByLabel('Enumerator name').fill('Test Enumerator');await page.getByRole('button',{name:'Save profile',exact:true}).click();await reloadAndReturn(page);assert(await page.getByLabel('Enumerator name').inputValue()==='Test Enumerator','Profile persistence failed');
await page.evaluate(()=>go('members'));await page.getByRole('button',{name:'Remove a member',exact:true}).click();await page.getByRole('button',{name:'Remove selected member'}).click();assert(await page.getByText('Add the first household member to start.').count()===1,'Removal failed');await page.evaluate(()=>go('review'));assert(await page.getByRole('button',{name:'Finish demo review'}).isDisabled(),'Empty household review allowed');
await page.evaluate(()=>go('home'));await page.getByLabel('Search households').fill('zzzzzz');await page.getByText(/No matching households/).waitFor();assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Mobile overflow');
assert(errors.length===0,errors.join('\n'));console.log(JSON.stringify({passed:true,pageErrors:errors,checks:['text edit scroll and DOM preservation','checkbox scroll preservation','conditional follow-up scroll preservation','new-screen scroll reset','all 18 sections','employment validation and branching','member and household reload context','exclusive multi-select','new household/member and name edit','all-form completion through UI','signature drawing and refusal clearing','typed signature','review completion and edit invalidation','callback persistence','JSON download','profile editing','member removal','search','mobile overflow']}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});

