let showErrors=false;
let renderedScreenKey=null;
data.profile ||= {name:'Jamie Dela Cruz',barangay:'Barangay Cogon'};
data.profile.barangay='Barangay Cogon';
try { const c=JSON.parse(sessionStorage.getItem('tala-context'));if(c&&data.households.some(h=>h.id===c.hid)){hid=c.hid;mid=c.mid} } catch {}
for(const h of data.households){h.answers ||= {};h.answers.barangay='Barangay Cogon';h.answers.head=h.head;h.answers.address=h.address;h.members ||= []}
// Preserve previously saved free-text evacuation areas when moving to a dropdown.
for(const h of data.households){const a=h.answers,options=FORM.find(f=>f.route==='disaster').fields.find(f=>f.key==='evacuation').options;if(a.evacuation&&!options.includes(a.evacuation)){a.evacuationOther=a.evacuation;a.evacuation='Other'}for(const record of [a,...h.members])if(record.phone)record.phone=formatPhone(record.phone)}
function save(){try{localStorage.setItem('tala-demo-v1',JSON.stringify(data));sessionStorage.setItem('tala-context',JSON.stringify({hid,mid}))}catch{toast('Storage unavailable. Your edits are only kept while this page is open.')}}
function go(r){disposeMap();route=r;showErrors=false;save();if(location.hash.slice(1)!==r)history.pushState(null,'','#'+r);render()}
window.onhashchange=()=>{disposeMap();route=location.hash.slice(1)||'home';showErrors=false;render()};
function targetFor(f,h=hh(),m=member()){return f.person?m:h.answers}
function visible(f,a){return !f.when||f.when(a)}
function errorFor(f,a){let v=a?.[f.key];if(!visible(f,a))return '';if(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length))return f.optional?'':'Choose or enter an answer.';if(typeof v==='string'&&!v.trim())return f.optional?'':'Enter a value.';if(f.type==='tel'&&!/^\d{4}-\d{3}-\d{4}$/.test(v))return 'Use 4-3-4 format: 0917-123-4567.';if(f.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<f.min||Number(v)>f.max||!Number.isInteger(Number(v))))return `Enter a whole number from ${f.min} to ${f.max}.`;if(f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))))return 'Enter a valid date.';if(f.past&&v>new Date().toISOString().slice(0,10))return 'Birth date cannot be in the future.';if(['select','choice'].includes(f.type)&&!f.options.includes(v))return 'Choose an available answer.';return ''}
function missing(f,a){return f.fields.filter(x=>errorFor(x,a))}
function invalidate(){if(hh().status==='Demo reviewed')hh().status='In progress';delete hh().reviewedAt}
function updateAnswer(k,v){let f=FORM.find(x=>x.route===route),a=targetFor(f);a[k]=v;if(['firstName','middleName','lastName','extension'].includes(k)){const name=[a.firstName,a.middleName,a.lastName,a.extension].filter(Boolean).map(x=>x.trim()).filter(Boolean).join(' ');if(f.person)a.name=name;else a.head=name;}for(const x of f.fields){if(!visible(x,a))delete a[x.key]};if(route==='household'){hh().head=a.head;hh().address=a.address}if(route==='visit'){hh().status=a.visitResult==='Callback'?'Callback':'In progress'}invalidate();save()}
function changeField(el,k){
  const f=FORM.find(x=>x.route===route),a=targetFor(f);
  const before=f.fields.filter(x=>visible(x,a)).map(x=>x.key).join('|');
  if(el.type==='tel')el.value=formatPhone(el.value);updateAnswer(k,el.value);
  const after=f.fields.filter(x=>visible(x,a)).map(x=>x.key).join('|');
  // Ordinary edits keep the existing DOM, focus, and pending clicks intact.
  if(before!==after)render();
  else {
    const wrap=el.closest('.question-wrap');
    if(k==='dob'){
      let hint=wrap.querySelector('.subtle');
      if(!hint){hint=document.createElement('p');hint.className='subtle';wrap.append(hint)}
      hint.textContent=el.value?age(el.value)+' years old · Calculated from date of birth':'';
    }
    if(showErrors){
      const field=f.fields.find(x=>x.key===k),error=errorFor(field,a);
      let message=wrap.querySelector('.error');
      if(error&&!message){message=document.createElement('p');message.className='error';message.setAttribute('role','alert');wrap.append(message)}
      if(message){if(error)message.textContent=error;else message.remove()}
    }
  }
}
function choose(k,v){updateAnswer(k,v);render()}
function multi(k,v,checked){let f=FORM.find(x=>x.route===route),a=targetFor(f),items=a[k]||[];const exclusive=['None','Prefer not to answer'];items=checked?(exclusive.includes(v)?[v]:[...items.filter(x=>!exclusive.includes(x)),v]):items.filter(x=>x!==v);updateAnswer(k,[...new Set(items)]);render()}
function renderField(f,a){if(!visible(f,a))return '';let v=a[f.key]??'',err=showErrors?errorFor(f,a):'',id='field-'+f.key,handler=`changeField(this,'${f.key}')`,input='';if(f.type==='photo'){input=pictureControl(a.photo,id,'household')}else if(f.type==='choice'){input=`<div class="segments" role="group" aria-label="${esc(f.label)}">${f.options.map(o=>`<button type="button" aria-pressed="${v===o}" class="${v===o?'selected':''}" onclick="choose('${f.key}',${esc(JSON.stringify(o))})">${esc(o)}</button>`).join('')}</div>`}else if(f.type==='multi'){input=`<div role="group" aria-label="${esc(f.label)}">${f.options.map(o=>`<label class="radio"><input type="checkbox" ${(Array.isArray(v)&&v.includes(o))?'checked':''} onchange="multi('${f.key}',${esc(JSON.stringify(o))},this.checked)">${esc(o)}</label>`).join('')}</div>`}else if(f.type==='select'){input=`<select id="${id}" class="field" onchange="${handler}"><option value="">Select answer</option>${f.options.map(o=>`<option ${v===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`}else if(f.type==='textarea'){input=`<textarea id="${id}" class="field" rows="3" oninput="updateAnswer('${f.key}',this.value)">${esc(v)}</textarea>`}else{input=`<input id="${id}" class="field" type="${f.type}" value="${esc(v)}" ${f.min!==undefined?`min="${f.min}" max="${f.max}" step="1"`:''} ${f.type==='tel'?'placeholder="0917-123-4567" inputmode="tel" maxlength="13"':''} ${f.past?`max="${new Date().toISOString().slice(0,10)}"`:''} oninput="updateAnswer('${f.key}',this.value)" onchange="${handler}">`};return `<div class="question-wrap"><label class="question" ${['choice','multi'].includes(f.type)?'':`for="${id}"`}>${esc(f.label)}</label>${input}${f.type==='tel'?'<p class="subtle">Format: 0917-123-4567 (4-3-4)</p>':''}${f.hint?`<p class="subtle">${esc(f.hint)}</p>`:''}${err?`<p class="error" role="alert">${err}</p>`:''}${f.key==='dob'&&v?`<p class="subtle">${age(v)} years old · Calculated from date of birth</p>`:''}</div>`}
function sectionState(i,h=hh()){let f=FORM[i];if(i===3)return {ok:h.members.length>0,detail:h.members.length+' members'};if(i===17){let ok=h.answers.consent==='Yes'&&!!(h.answers.signature||h.answers.signedName?.trim());return {ok,detail:ok?'Consent recorded':h.answers.consent==='No'?'Respondent declined':'Consent and signature needed'}}if(f.person){let ready=h.members.filter(m=>!missing(f,m).length).length;return {ok:h.members.length>0&&ready===h.members.length,detail:`${ready} of ${h.members.length} members ready`}}let n=missing(f,h.answers).length;return {ok:n===0,detail:n?`${n} required answers missing`:'Ready for review'}}
function requirements(){return FORM.map((f,i)=>({label:sections[i],route:f.route,...sectionState(i)}))}
function openSection(i){let f=FORM[i];if(f.person&&!hh().members.length){toast('Add a household member first.');return go('members')}if(f.person){let bad=hh().members.findIndex(m=>missing(f,m).length);mid=bad<0?0:bad}go(f.route)}
function nextForm(){let i=FORM.findIndex(f=>f.route===route),f=FORM[i];showErrors=true;if(missing(f,targetFor(f)).length){render();$('.error')?.scrollIntoView({block:'center'});return toast('Complete the highlighted answers.')}save();if(f.person){if(route==='demographics')return go('education');if(route==='education')return go('employment');return go('members')}openSection(Math.min(i+1,17))}
function memberTabs(){return `<div class="tabs" aria-label="Member sections">${[4,7,8,5,6].map(i=>`<button class="${route===FORM[i].route?'active':''}" onclick="go('${FORM[i].route}')">${sections[i]}</button>`).join('')}</div>`}
function render(){
if(!hh()&&!['home','households','map','reports','profile','welcome'].includes(route)){route='home';history.replaceState(null,'','#home')}
if(!hh()&&data.households.length)hid=data.households[0].id;
disposeMap();
const screenKey=route+'|'+hid+'|'+mid;
const keepPosition=screenKey===renderedScreenKey;
const scrollTop=keepPosition?($('.scroll')?.scrollTop||0):0;
const tabScroll=keepPosition?($('.tabs')?.scrollLeft||0):0;
const focusedId=keepPosition&&$('#app').contains(document.activeElement)?document.activeElement.id:'';
let h=hh(),a=h?.answers||{},m=member(),body='',f=FORM.find(f=>f.route===route);if(f?.person&&!m){route='members';f=FORM[3]}
if(route==='location'){body=locationScreen()}
else if(route==='map'){body=mapScreen()}
else if(f&&f.fields.length){let t=targetFor(f);body=shell(f.person?member().name:sections[FORM.indexOf(f)],f.person?`Member ${mid+1} of ${h.members.length} · ${h.id}`:h.id,`${f.person?`<label class="subtle" for="member-switch">Household member</label><select class="field" id="member-switch" onchange="mid=Number(this.value);save();showErrors=false;render()">${h.members.map((p,i)=>`<option value="${i}" ${i===mid?'selected':''}>${esc(p.name)}</option>`).join('')}</select>${memberTabs()}`:`<span class="overline">SECTION ${FORM.indexOf(f)+1} OF 18</span>`}<h3>${sections[FORM.indexOf(f)]}</h3>${route==='housing'?'<div class="notice observation">◉ Observation · Record dwelling materials from observation.</div>':''}${route==='employment'?'<p class="subtle">Record this member’s work situation. For children, the respondent can select “No” and “Below working age.”</p>':''}${f.fields.map(x=>renderField(x,t)).join('')}<p class="subtle tiny" style="margin-top:20px">Prototype questions · Changes save on this browser.</p>`,true,f.person?'members':'sections',actions(f.person?'members':'sections','nextForm()',f.person&&!['demographics','education'].includes(route)?'Save member':'Save & continue'))}
else if(route==='home'||route==='households'){let reviewed=data.households.filter(x=>x.status==='Demo reviewed').length;body=shell(route==='home'?`Magandang araw, ${data.profile.name.split(' ')[0]}.`:'Households',`${data.profile.barangay} · Field enumerator`,`${route==='home'?`<div class="hero-card"><span class="overline">YOUR COMMUNITY, AT A GLANCE</span><h2>Small visits.<br>A fuller picture.</h2><p>Continue where you left off today.</p></div><div class="stats"><div class="stat"><b>${data.households.length}</b><span>Registered Households</span></div><div class="stat"><b>${reviewed}</b><span>Reviewed</span></div><div class="stat"><b>${data.households.filter(x=>x.status==='Callback').length}</b><span>Callback</span></div></div>${dashboardDetails()}`:''}<div class="heading-row"><h3>Your households</h3><span class="pill">Local demo</span></div><input class="search" aria-label="Search households" placeholder="Search name or household ID" value="${esc(query)}" oninput="query=this.value;document.getElementById('house-list').innerHTML=householdList()"><div class="filters">${['All','In progress','Callback','Demo reviewed'].map(v=>`<button class="filter ${filter===v?'active':''}" onclick="filter='${v}';render()">${v==='Demo reviewed'?'Reviewed':v}</button>`).join('')}</div><div id="house-list">${householdList()}</div><button class="primary wide" onclick="newHouse()">＋ Register a household</button>${removedHousehold?'<button class="link wide" onclick="restoreRemovedHousehold()">Undo last household removal</button>':''}<p class="subtle tiny" style="margin-top:16px">Fictional information only · Stored on this browser</p>`,false,'')}
else if(route==='overview'){let req=requirements(),n=req.filter(r=>r.ok).length;body=shell(h.id,`${a.barangay||data.profile.barangay} · Household overview`,`<span class="overline">HOUSEHOLD RECORD</span><h2 style="margin:8px 0">${esc(h.head)}</h2><p class="subtle">${esc(h.address)}</p><div class="card"><strong>${n} of 18 sections ready</strong><div class="progress"><span style="width:${n/18*100}%"></span></div><span class="subtle">${h.members.length} members · ${h.status}</span></div>${a.callbackDate&&a.visitResult==='Callback'?`<div class="notice">Callback: ${esc(a.callbackDate.replace('T',' '))}</div>`:''}<button class="card row-card" onclick="go('household')"><span class="house-icon">⌂</span><span><strong>Edit household profile</strong><small>Head, address and respondent</small></span><span class="chevron">›</span></button><button class="card row-card" onclick="go('members')"><span class="house-icon">♧</span><span><strong>Household members</strong><small>Demographics, education and employment</small></span><span class="chevron">›</span></button><button class="card row-card" onclick="go('sections')"><span class="house-icon">≡</span><span><strong>Interview sections</strong><small>18 working prototype sections</small></span><span class="chevron">›</span></button><button class="primary wide" onclick="openSection(${Math.max(0,req.findIndex(r=>!r.ok))})">Continue interview →</button>${locationCard(h)}<button class="secondary wide" onclick="exportData(true)">Export household JSON</button><button class="danger wide" onclick="removeHouseholdDialog()">Remove household</button>`)}
else if(route==='members'){body=shell(h.id,'Household members',`<div class="heading-row" style="margin-top:0"><h3>Every member counts.</h3><span class="subtle">${h.members.length} members</span></div>${h.members.length?'':'<p class="empty">Add the first household member to start.</p>'}${h.members.map((p,i)=>{let n=FORM.filter(f=>f.person&&!missing(f,p).length).length;return `<button class="card row-card" onclick="mid=${i};go('demographics')"><span class="initials">${esc(p.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.relationship||'Member')} · ${age(p.dob)} years old</small><span class="badge ${n===5?'done':''}">${n===5?'✓':'●'} ${n} of 5 member sections ready</span></span><span class="chevron">›</span></button>`}).join('')}<button class="secondary wide" onclick="newMember()">＋ Add household member</button>${h.members.length?'<button class="link wide" onclick="removeMemberDialog()">Remove a member</button>':''}`,true,'overview')}
else if(route==='sections'){body=shell(h.id,'Interview sections',`<h3>A step at a time.</h3><p class="subtle">${requirements().filter(x=>x.ok).length} of 18 sections ready</p>${sections.map((s,i)=>{let state=sectionState(i);return `<button class="card row-card ${state.ok?'complete':''}" onclick="openSection(${i})"><span class="section-num">${state.ok?'✓':i+1}</span><span><strong>${s}</strong><small>${state.detail}</small></span><span class="chevron">›</span></button>`}).join('')}`,true,'overview')}
else if(route==='consent'){body=shell(h.id,'Consent & review',`<span class="overline">SECTION 18 OF 18</span><h2 style="margin-top:10px">An informed decision.</h2><div class="notice">Review the statement with the respondent.<button class="secondary wide" onclick="consentStatement()">View demo consent statement</button></div><label class="question">Does the respondent agree?</label><div class="segments">${['Yes','No'].map(v=>`<button class="${a.consent===v?'selected':''}" aria-pressed="${a.consent===v}" onclick="setConsent('${v}')">${v}</button>`).join('')}</div>${a.consent==='Yes'?`<label class="question">Demo respondent signature</label><canvas id="signature" width="600" height="240" aria-label="Signature drawing area"></canvas><button class="link" onclick="delete hh().answers.signature;invalidate();save();render()">Clear signature</button><label class="question" for="signed-name">Or type a fictional name as your signature</label><input class="field" id="signed-name" value="${esc(a.signedName||'')}" oninput="hh().answers.signedName=this.value;invalidate();save()"><p class="subtle tiny">Either a drawn mark or typed name completes this demo step.</p>`:a.consent==='No'?'<div class="notice" style="margin-top:20px">Refusal recorded. No signature is requested. The interview remains a draft and cannot be marked reviewed.</div>':''}`,true,'sections',actions('sections',"go('review')",'Review interview'))}
else if(route==='review'){let req=requirements(),ok=req.every(x=>x.ok);body=shell(h.id,'Review before finishing',`<h2>One last look.</h2><p class="subtle">${req.filter(x=>x.ok).length} of 18 sections ready</p>${req.map((r,i)=>`<button class="card row-card" onclick="openSection(${i})"><span style="color:${r.ok?'var(--green)':'var(--amber)'}">${r.ok?'✓':'○'}</span><span><strong>${r.label}</strong><small>${r.detail}</small></span><span class="chevron">›</span></button>`).join('')}<div class="notice">Review covers all prototype fields. Official questionnaire codes and legal consent wording still need verification.</div><button class="primary wide" ${ok?'':'disabled'} onclick="finishReview()">Finish demo review</button>`,true,'sections')}
else if(route==='reports'){body=shell('Field summary','Local prototype records',`<h2>Your progress, clearly.</h2><div class="card"><dl><dt>Households</dt><dd>${data.households.length}</dd><dt>Registered members</dt><dd>${data.households.reduce((n,h)=>n+h.members.length,0)}</dd><dt>Reviewed</dt><dd>${data.households.filter(h=>h.status==='Demo reviewed').length}</dd><dt>Callbacks</dt><dd>${data.households.filter(h=>h.status==='Callback').length}</dd></dl></div>${data.households.map(h=>`<button class="card row-card" onclick="hid='${h.id}';go('overview')"><span><strong>${esc(h.head)}</strong><small>${FORM.filter((f,i)=>sectionState(i,h).ok).length}/18 sections ready · ${h.status}</small></span></button>`).join('')}<button class="primary wide" onclick="exportData(false)">Export demo records JSON</button>`,false,'home')}
else if(route==='profile'){body=shell('Your workspace','Field enumerator',`<h3>Enumerator Profile</h3>${pictureControl(data.profile.photo,'profile-photo','enumerator')}<form id="profile-form"><label class="question" for="profile-name">Enumerator name</label><input id="profile-name" class="field" required value="${esc(data.profile.name)}"><label class="question" for="profile-barangay">Barangay</label><input id="profile-barangay" class="field" readonly required value="${esc(data.profile.barangay)}"><button class="primary wide">Save profile</button></form><p class="subtle" style="margin-top:20px">Fictional data stays on this browser. No authentication or server synchronization is connected.</p><button class="secondary wide" onclick="go('welcome')">View welcome screen</button><button class="secondary wide" onclick="resetDemo()">Reset demo data</button>`,false,'home')}
else if(route==='welcome'){body=`<div class="welcome"><span class="brandmark">⌂</span><span class="overline">KNOW YOUR COMMUNITY</span><h2>Welcome to Tala.</h2><p>Barangay inhabitants registry<br>A little less paperwork.<br>More time for your community.</p><button class="primary wide" onclick="go('home')">Enter demo →</button><p class="tiny" style="margin-top:20px">Fictional records · No account required</p></div>`}
else{route='home';return render()}
$('#app').innerHTML=body;
renderedScreenKey=route+'|'+hid+'|'+mid;
if(keepPosition){
  if(focusedId)document.getElementById(focusedId)?.focus({preventScroll:true});
  if($('.scroll'))$('.scroll').scrollTop=scrollTop;
  if($('.tabs'))$('.tabs').scrollLeft=tabScroll;
}
if(route==='location'||route==='map')mountMap();
if(route==='consent'&&a.consent==='Yes')setupSignature();if(route==='profile')$('#profile-form').onsubmit=e=>{e.preventDefault();let name=$('#profile-name').value.trim(),barangay=$('#profile-barangay').value.trim();if(!name||!barangay)return toast('Enter a name and barangay.');data.profile={...data.profile,name,barangay:'Barangay Cogon'};save();toast('Profile saved.');render()};}
function formatPhone(value){const digits=value.replace(/\D/g,'');if(digits.length!==11)return value;return digits.slice(0,4)+'-'+digits.slice(4,7)+'-'+digits.slice(7)}
function pictureControl(photo,id,target){return `<div class="picture-control">${photo?`<img class="profile-picture" src="${esc(photo)}" alt="${target==='enumerator'?'Enumerator':'Household'} profile picture">`:'<div class="picture-placeholder" aria-hidden="true">'+icon('profile')+'</div>'}<label class="question" for="${id}">Choose Picture (Optional)</label><input class="field" id="${id}" type="file" accept="image/jpeg,image/png,image/webp" onchange="uploadPicture(this,'${target}')">${photo?`<button class="link" onclick="removePicture('${target}')">Remove Picture</button>`:''}<p class="subtle">JPG, PNG or WebP, up to 5 MB.</p></div>`}
async function uploadPicture(input,target){
 const file=input.files[0];if(!file)return;
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){input.value='';return toast('Choose a JPG, PNG or WebP image up to 5 MB.')}
 const household=hh(),profile=data.profile;
 try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,480/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const photo=canvas.toDataURL('image/jpeg',0.8);if(target==='enumerator')profile.photo=photo;else{household.answers.photo=photo;if(household.status==='Demo reviewed')household.status='In progress';delete household.reviewedAt}save();render();toast('Picture saved.')}catch{toast('Unable to read this image. Try another picture.')}
}
function removePicture(target){if(target==='enumerator')delete data.profile.photo;else{delete hh().answers.photo;invalidate()}save();render()}
function dashboardDetails(){const members=data.households.flatMap(h=>h.members),male=members.filter(m=>m.sex==='Male').length,female=members.filter(m=>m.sex==='Female').length;return `<div class="stats" aria-label="Member Counts"><div class="stat"><b>${members.length}</b><span>Total Members</span></div><div class="stat"><b>${male}</b><span>Male</span></div><div class="stat"><b>${female}</b><span>Female</span></div></div>${members.length-male-female?`<p class="subtle">${members.length-male-female} members have no sex recorded.</p>`:''}<div class="card enumerator-card">${data.profile.photo?`<img class="profile-picture" src="${esc(data.profile.photo)}" alt="Enumerator profile picture">`:'<span class="initials">'+esc(data.profile.name.split(' ').map(n=>n[0]).slice(0,2).join(''))+'</span>'}<div><h3>Enumerators’ Data</h3><strong>${esc(data.profile.name)}</strong><p class="subtle">${esc(data.profile.barangay)}</p><button class="link" onclick="go('profile')">Edit Profile / Picture</button></div></div>`}
function setConsent(v){if(hh().answers.consent!==v){delete hh().answers.signature;delete hh().answers.signedName}hh().answers.consent=v;invalidate();save();render()}
function finishReview(){if(!requirements().every(r=>r.ok)){toast('Complete all required fields first.');return render()}hh().status='Demo reviewed';hh().reviewedAt=new Date().toISOString();save();toast('Demo reviewed. All records remain local.');go('overview')}
function exportData(single){let blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),prototype:true,households:single?[hh()]:data.households},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=single?hh().id+'.json':'tala-demo-records.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Demo export downloaded.')}
function removeMemberDialog(){modal(`<h3>Remove a member</h3><p class="subtle">This deletes the selected member’s answers from this demo household.</p><label class="question" for="remove-member">Member</label><select class="field" id="remove-member">${hh().members.map((m,i)=>`<option value="${i}">${esc(m.name)}</option>`).join('')}</select><button id="confirm-remove" class="primary wide">Remove selected member</button><button class="secondary wide" onclick="$('#modal').close()">Cancel</button>`);$('#confirm-remove').onclick=()=>{hh().members.splice(Number($('#remove-member').value),1);mid=0;invalidate();save();$('#modal').close();render()}}
function newHouse(){modal(`<h3>Register a household</h3><form id="new-house"><label class="question" for="head">Household head</label><input id="head" name="head" class="field" required maxlength="80"><label class="question" for="address">Address / purok</label><input id="address" name="address" class="field" required maxlength="150"><button class="primary wide">Create household</button><button type="button" class="secondary wide" onclick="$('#modal').close()">Cancel</button></form>`);$('#new-house').onsubmit=e=>{e.preventDefault();let values=new FormData(e.target),head=values.get('head').trim(),address=values.get('address').trim();if(!head||!address)return toast('Enter a name and address.');data.nextHouseholdNumber=Math.max(data.nextHouseholdNumber||455,...data.households.map(h=>Number(h.id.slice(3))+1));hid='HH-'+String(data.nextHouseholdNumber++).padStart(5,'0');mid=0;data.households.push({id:hid,head,address,status:'In progress',members:[],answers:{head,address,enumerator:data.profile.name,barangay:data.profile.barangay,interviewDate:new Date().toISOString().slice(0,10)}});save();$('#modal').close();go('setup')}}
function newMember(){modal(`<h3>Add household member</h3><form id="new-member"><label class="question" for="name">Full name</label><input class="field" id="name" name="name" required maxlength="80"><button class="primary wide">Add member</button><button type="button" class="secondary wide" onclick="$('#modal').close()">Cancel</button></form>`);$('#new-member').onsubmit=e=>{e.preventDefault();let name=new FormData(e.target).get('name').trim();if(!name)return toast('Enter a member name.');hh().members.push({name});mid=hh().members.length-1;invalidate();save();$('#modal').close();go('demographics')}}
function resetDemo(){modal('<h3>Reset demo data?</h3><p>This removes your edits and restores the fictional households.</p><button class="primary wide" id="reset-confirm">Reset demo</button><button class="secondary wide" onclick="document.getElementById(\'modal\').close()">Cancel</button>');$('#reset-confirm').onclick=()=>{locationDrafts.clear();removedHousehold=null;data=structuredClone(seed);data.profile={name:'Jamie Dela Cruz',barangay:'Barangay Cogon'};for(let h of data.households){h.answers.head=h.head;h.answers.address=h.address}hid=data.households[0].id;mid=0;filter='All';query='';save();$('#modal').close();go('home')}}
// Persist a visible mark only; tapping a blank canvas does not sign the form.
function setupSignature(){const c=$('#signature'),ctx=c.getContext('2d');let drawing=false,moved=false;ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#172944';if(hh().answers.signature){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0);img.src=hh().answers.signature}const point=e=>{let r=c.getBoundingClientRect();return [(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};c.onpointerdown=e=>{drawing=true;moved=false;c.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e))};c.onpointermove=e=>{if(drawing){moved=true;ctx.lineTo(...point(e));ctx.stroke()}};const finish=()=>{if(drawing&&moved){hh().answers.signature=c.toDataURL();invalidate();save()}drawing=false};c.onpointerup=finish;c.onpointercancel=finish;}
render();
// Clear closed dialogs so stale form controls are absent from the accessibility tree.
$('#modal').addEventListener('close',()=>{if(!$('#modal').open)$('#modal').replaceChildren()});


